[package]
name = "flow-backend"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
flow-engine = { path = "../flow-engine" }
flow-dto = { path = "../flow-dto" }
flow-store = { path = "../flow-store" }
flow-pg = { path = "../flow-pg" }
